# docker-compose.yml
# version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: literature_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: not1root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: